COESA_density – standard-atmosphere
COESA_density Function
20 statements
Source File
public function COESA_density(Z) result(density)
a simple version that just returns density
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: Z
altitude in meters
Return Value real(kind=wp)
kg/m^3
Calls
Contents
Source Code
COESA_density
Source Code
function COESA_density(Z) result(density)
    !! a simple version that just returns density
    real(wp),intent(in) :: Z !! altitude in meters
    real(wp) :: density !! kg/m^3
    real(wp) :: H,M,T,P
    if (Z < -5000.0_wp) then
        error stop "altitude below lower bound of -5000 m"
    else if (Z > 1000000.0_wp) then
        error stop "altitude above upper bound of 1000000 m"
    else if (Z < 86000.0_wp) then
        H = geopotential_altitude(Z)
        M = mean_molecular_weight_lower(Z)
        T = temperature_lower(H, M)
        P = pressure_lower(H)
    else
        T = temperature_upper(Z)
        P = pressure_upper(Z)
        M = mean_molecular_weight_upper(Z)
    end if
    density = P * M / (Rstar * T)
end function COESA_density
Call graph
coesa_density calls pressure_upper, pressure_lower, temperature_upper, mean_molecular_weight_upper, geopotential_altitude, temperature_lower, mean_molecular_weight_lower
pressure_upper calls interpolation_index, interpolation_scale_factors
pressure_lower calls findb
mean_molecular_weight_upper calls interpolation_index, interpolation_scale_factors
temperature_lower calls tm
mean_molecular_weight_lower calls mean_molecular_weight_ratio_lower
tm calls findb
interpolation_index calls find
mean_molecular_weight_ratio_lower calls find
findb calls find