COESA_atmosphere – standard-atmosphere
COESA_atmosphere Function
22 statements
Source File
public function COESA_atmosphere(Z) result(s)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: Z
Return Value type(State)
Calls
Contents
Source Code
COESA_atmosphere
Source Code
function COESA_atmosphere(Z) result(s)
    real(wp),intent(in) :: Z ! altitude in meters
    type(state) :: s
    real(wp) :: H,M,T,P,c
    if (Z < -5000.0_wp) then
        error stop "altitude below lower bound of -5000 m"
    else if (Z > 1000000.0_wp) then
        error stop "altitude above upper bound of 1000000 m"
    else if (Z < 86000.0_wp) then
        H = geopotential_altitude(Z)
        M = mean_molecular_weight_lower(Z)
        T = temperature_lower(H, M)
        P = pressure_lower(H)
        c = speed_of_sound_lower(T, M)
    else
        T = temperature_upper(Z)
        P = pressure_upper(Z)
        M = mean_molecular_weight_upper(Z)
        c = speed_of_sound_86km()
    end if
    s = State(M, T, P, c)
end function COESA_atmosphere
Call graph
coesa_atmosphere calls pressure_upper, pressure_lower, speed_of_sound_86km, temperature_upper, mean_molecular_weight_upper, speed_of_sound_lower, geopotential_altitude, temperature_lower, mean_molecular_weight_lower
pressure_upper calls interpolation_index, interpolation_scale_factors
pressure_lower calls findb
speed_of_sound_86km calls speed_of_sound_lower, geopotential_altitude, temperature_lower, mean_molecular_weight_lower
mean_molecular_weight_upper calls interpolation_index, interpolation_scale_factors
temperature_lower calls tm
mean_molecular_weight_lower calls mean_molecular_weight_ratio_lower
tm calls findb
interpolation_index calls find
mean_molecular_weight_ratio_lower calls find
findb calls find