findb – standard-atmosphere
findb Function
12 statements
Source File
private pure function findb(H) result(b)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: H
Return Value integer
Called by
Contents
Source Code
findb
Source Code
pure function findb(H) result(b)
    real(wp),intent(in) :: H
    integer :: b
    integer :: i
    i = 1
    ! do while (i < size(Hb) .and. H > Hb(i + 1))
    !     i = i + 1
    ! end do
    do
        if (i >= size(Hb)) exit
        if (H <= Hb(i + 1)) exit
        i = i + 1
    end do
    b = i - 1
end function findb
Call graph
tm calls findb
pressure_lower calls findb
temperature_lower calls tm
coesa_density calls pressure_lower, temperature_lower
coesa_atmosphere calls pressure_lower, temperature_lower, speed_of_sound_86km
speed_of_sound_86km calls temperature_lower