find – standard-atmosphere
find Function
11 statements
Source File
private pure function find(x, xvec) result(i)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: x
real(kind=wp), intent(in), dimension(:) :: xvec
Return Value integer
Called by
Contents
Source Code
find
Source Code
pure function find(x, xvec) result(i)
    real(wp),intent(in) :: x
    real(wp),dimension(:),intent(in) :: xvec
    integer :: i
    i = 1
    do
        if (i >= size(xvec)) exit
        if (x <= xvec(i + 1)) exit
        i = i + 1
    end do
end function find
Call graph
mean_molecular_weight_ratio_lower calls find
interpolation_index calls find
findb calls find
tm calls findb
pressure_upper calls interpolation_index
pressure_lower calls findb
mean_molecular_weight_upper calls interpolation_index
mean_molecular_weight_lower calls mean_molecular_weight_ratio_lower
coesa_atmosphere calls pressure_upper, pressure_lower, mean_molecular_weight_upper, mean_molecular_weight_lower, speed_of_sound_86km, temperature_lower
speed_of_sound_86km calls mean_molecular_weight_lower, temperature_lower
coesa_density calls pressure_upper, pressure_lower, mean_molecular_weight_upper, mean_molecular_weight_lower, temperature_lower
temperature_lower calls tm