geopotential_altitude – standard-atmosphere
geopotential_altitude Function
4 statements
Source File
private pure function geopotential_altitude(Z)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: Z
Return Value real(kind=wp)
Called by
Contents
Source Code
geopotential_altitude
Source Code
pure real(wp) function geopotential_altitude(Z)
    real(wp),intent(in) :: Z
    geopotential_altitude = r0 * Z / (r0 + Z)
end function geopotential_altitude
Call graph
coesa_density calls geopotential_altitude
coesa_atmosphere calls geopotential_altitude, speed_of_sound_86km
speed_of_sound_86km calls geopotential_altitude