interpolation_index – standard-atmosphere
interpolation_index Function
5 statements
Source File
private pure function interpolation_index(Z) result(i)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: Z
Return Value integer
Calls
Called by
Contents
Source Code
interpolation_index
Source Code
pure integer function interpolation_index(Z) result(i)
    real(wp),intent(in) :: Z
    ! Find the index for the lower side of the altitude interval
    i = find(Z, Ztableupper)
    ! We are going to reference all elements from i - 1 to i + 1, so we need to
    ! adjust the index away from the boundaries
    if (i==1) i = 2
end function interpolation_index
Call graph
interpolation_index calls find
pressure_upper calls interpolation_index
mean_molecular_weight_upper calls interpolation_index
coesa_atmosphere calls pressure_upper, mean_molecular_weight_upper
coesa_density calls pressure_upper, mean_molecular_weight_upper