interpolation_scale_factors – standard-atmosphere
interpolation_scale_factors Subroutine
12 statements
Source File
private pure subroutine interpolation_scale_factors(i, Z, scale0, scale1, scale2)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i
real(kind=wp), intent(in) :: Z
real(kind=wp), intent(out) :: scale0
real(kind=wp), intent(out) :: scale1
real(kind=wp), intent(out) :: scale2
Called by
Contents
Source Code
interpolation_scale_factors
Source Code
pure subroutine interpolation_scale_factors(i, Z, scale0, scale1, scale2)
    integer,intent(in) :: i
    real(wp),intent(in) :: Z
    real(wp),intent(out) :: scale0, scale1, scale2
    real(wp) :: Z0,Z1,Z2
    Z0 = Ztableupper(i - 1)
    Z1 = Ztableupper(i)
    Z2 = Ztableupper(i + 1)
    scale0 = (Z - Z1) * (Z - Z2) / ((Z0 - Z1) * (Z0 - Z2))
    scale1 = (Z - Z0) * (Z - Z2) / ((Z1 - Z0) * (Z1 - Z2))
    scale2 = (Z - Z0) * (Z - Z1) / ((Z2 - Z0) * (Z2 - Z1))
end subroutine interpolation_scale_factors
Call graph
pressure_upper calls interpolation_scale_factors
mean_molecular_weight_upper calls interpolation_scale_factors
coesa_atmosphere calls pressure_upper, mean_molecular_weight_upper
coesa_density calls pressure_upper, mean_molecular_weight_upper