mean_molecular_weight_ratio_lower – standard-atmosphere
mean_molecular_weight_ratio_lower Function
12 statements
Source File
private pure function mean_molecular_weight_ratio_lower(Z)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: Z
Return Value real(kind=wp)
Calls
Called by
Contents
Source Code
mean_molecular_weight_ratio_lower
Source Code
pure real(wp) function mean_molecular_weight_ratio_lower(Z)
    real(wp),intent(in) :: Z
    integer :: i
    if (Z < Ztable(1)) then
        mean_molecular_weight_ratio_lower = 1.0_wp
    else if (Z > Ztable(size(Ztable))) then
        error stop "altitude above maximum value in table"
    else
        i = find(Z, Ztable)
        mean_molecular_weight_ratio_lower = &
            Mratiotable(i) + (Mratiotable(i + 1) - Mratiotable(i)) / &
            (Ztable(i + 1) - Ztable(i)) * (Z - Ztable(i))
    end if
end function mean_molecular_weight_ratio_lower
Call graph
mean_molecular_weight_ratio_lower calls find
mean_molecular_weight_lower calls mean_molecular_weight_ratio_lower
coesa_density calls mean_molecular_weight_lower
coesa_atmosphere calls mean_molecular_weight_lower, speed_of_sound_86km
speed_of_sound_86km calls mean_molecular_weight_lower