mean_molecular_weight_upper – standard-atmosphere
mean_molecular_weight_upper Function
11 statements
Source File
private pure function mean_molecular_weight_upper(Z)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: Z
Return Value real(kind=wp)
Calls
Called by
Contents
Source Code
mean_molecular_weight_upper
Source Code
pure real(wp) function mean_molecular_weight_upper(Z)
    real(wp),intent(in) :: Z
    integer :: i
    real(wp) :: M0,M1,M2,scale0,scale1,scale2
    i = interpolation_index(Z)
    call interpolation_scale_factors(i, Z, scale0, scale1, scale2)
    M0 = Mtableupper(i - 1)
    M1 = Mtableupper(i)
    M2 = Mtableupper(i + 1)
    mean_molecular_weight_upper = M0 * scale0 + M1 * scale1 + M2 * scale2
end function mean_molecular_weight_upper
Call graph
mean_molecular_weight_upper calls interpolation_index, interpolation_scale_factors
coesa_density calls mean_molecular_weight_upper
coesa_atmosphere calls mean_molecular_weight_upper