pressure_lower – standard-atmosphere
pressure_lower Function
11 statements
Source File
private pure function pressure_lower(H)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: H
Return Value real(kind=wp)
Calls
Called by
Contents
Source Code
pressure_lower
Source Code
pure real(wp) function pressure_lower(H)
    real(wp),intent(in) :: H
    integer :: i, b
    b = findb(H)
    i = b + 1
    if (Lmb(i) == 0) then
        pressure_lower = Pb(i) * exp(-g0 * M0 * (H - Hb(i)) / (Rstar * Tmb(i)))
    else
        pressure_lower = Pb(i) * (Tmb(i) / (Tmb(i) + Lmb(i) * (H - Hb(i)))) ** (g0 * M0 / (Rstar * Lmb(i)))
    end if
end function pressure_lower
Call graph
pressure_lower calls findb
findb calls find
coesa_density calls pressure_lower
coesa_atmosphere calls pressure_lower