pressure_upper – standard-atmosphere
pressure_upper Function
12 statements
Source File
private pure function pressure_upper(Z)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: Z
Return Value real(kind=wp)
Calls
Called by
Contents
Source Code
pressure_upper
Source Code
pure real(wp) function pressure_upper(Z)
    real(wp),intent(in) :: Z
    integer :: i
    real(wp) :: logP0,logP1,logP2,logP,scale0,scale1,scale2
    i = interpolation_index(Z)
    call interpolation_scale_factors(i, Z, scale0, scale1, scale2)
    logP0 = logPtableupper(i - 1)
    logP1 = logPtableupper(i)
    logP2 = logPtableupper(i + 1)
    logP = logP0 * scale0 + logP1 * scale1 + logP2 * scale2
    pressure_upper = exp(logP)
end function pressure_upper
Call graph
pressure_upper calls interpolation_index, interpolation_scale_factors
interpolation_index calls find
coesa_density calls pressure_upper
coesa_atmosphere calls pressure_upper