speed_of_sound_lower – standard-atmosphere
speed_of_sound_lower Function
4 statements
Source File
private pure function speed_of_sound_lower(T, M)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: T
real(kind=wp), intent(in) :: M
Return Value real(kind=wp)
Called by
Source Code
pure real(wp) function speed_of_sound_lower(T, M)
    real(wp),intent(in) :: T, M
    speed_of_sound_lower = sqrt(gamma * Rstar * T / M)
end function speed_of_sound_lower
Call graph
coesa_atmosphere calls speed_of_sound_lower, speed_of_sound_86km
speed_of_sound_86km calls speed_of_sound_lower