speed_of_sound_86km – standard-atmosphere
speed_of_sound_86km Function
8 statements
Source File
private pure function speed_of_sound_86km()
Arguments
None
Return Value real(kind=wp)
Calls
Called by
Contents
Source Code
speed_of_sound_86km
Source Code
pure real(wp) function speed_of_sound_86km()
    real(wp),parameter :: Z = 86000.0_wp ! (m)
    real(wp) :: H,M,T
    H = geopotential_altitude(Z)
    M = mean_molecular_weight_lower(Z)
    T = temperature_lower(H, M)
    speed_of_sound_86km = speed_of_sound_lower(T, M)
end function speed_of_sound_86km
Call graph
speed_of_sound_86km calls geopotential_altitude, temperature_lower, mean_molecular_weight_lower, speed_of_sound_lower
temperature_lower calls tm
mean_molecular_weight_lower calls mean_molecular_weight_ratio_lower
tm calls find
mean_molecular_weight_ratio_lower calls find
coesa_atmosphere calls speed_of_sound_86km