temperature_lower – standard-atmosphere
temperature_lower Function
5 statements
Source File
private pure function temperature_lower(H, M)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: H
real(kind=wp), intent(in) :: M
Return Value real(kind=wp)
Calls
Called by
Contents
Source Code
temperature_lower
Source Code
pure real(wp) function temperature_lower(H, M)
    real(wp),intent(in) :: H
    real(wp),intent(in) :: M
    temperature_lower = Tm(H) / M0 * M
end function temperature_lower
Call graph
temperature_lower calls tm
tm calls find
coesa_atmosphere calls temperature_lower, speed_of_sound_86km
coesa_density calls temperature_lower
speed_of_sound_86km calls temperature_lower