Tm – standard-atmosphere
Tm Function
6 statements
Source File
private pure function Tm(H)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: H
Return Value real(kind=wp)
Calls
Called by
Source Code
pure real(wp) function Tm(H)
    real(wp),intent(in) :: H
    integer :: i
    i = find(H, Hb)
    Tm = Tmb(i) + Lmb(i) * (H - Hb(i))
end function Tm
Call graph
tm calls find
temperature_lower calls tm
coesa_atmosphere calls temperature_lower, speed_of_sound_86km
coesa_density calls temperature_lower
speed_of_sound_86km calls temperature_lower